global:
  resolve_timeout: 5m

route:
  group_by: ['alertname', 'instance']
  group_wait: 2m
  group_interval: 2m
  repeat_interval: 1h
  receiver: 'default'

  routes:
    - matchers:
        - type="create_worker"
      receiver: 'create_worker'
    - matchers:
        - severity="warning"
      receiver: 'warning'

receivers:
  - name: 'default'
    webhook_configs:
      - url: 'http://localhost:8000/alerts'
  - name: 'create_worker'
    webhook_configs:
      - url: 'http://localhost:8000/prometheus/create'
  - name: 'warning'
    webhook_configs:
      - url: 'http://localhost:8000/alerts/warning'