global:
  scrape_interval: 15s

rule_files:
  - alert_rules.yml

alerting:
  alertmanagers:
    - static_configs:
      - targets: ['localhost:9093']
      
scrape_configs:
  - job_name: 'master'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['localhost:8000']

