global:
  scrape_interval: 15s

rule_files:
  - alert_rules.yml

alerting:
  alertmanagers:
    - static_configs:
      - targets: ['localhost:9093']
      
scrape_configs:
  - job_name: 'master'
    metrics_path: '/metrics'
    file_sd_configs:
      - refresh_interval: "5m"
        files:
          - 'targets.json'

